### ISSUE TITLE
[BUG]Safari 박스 이동

### ISSUE THREAD

**Issue by WhiteHyun** [MBTImaker/MBTImaker-javascript-frontend#314]
## 증상

- 사파리 앱에서 남은 문항 관련 박스 위치 이동

## 시나리오

1. 테스트 시작 버튼 클릭
2. 위로 올렸다 내렸다를 반복
3. 남은 문항에 대한 박스가 이동함

## 예상되는 부작용

- 단순 버그

## Video

https://user-images.githubusercontent.com/57972338/147190762-cb1ed953-1bb5-4d67-a4e4-c4e9a4da1aa2.mp4

**Comment by hotbreakb** [comment]
이슈 남겨주셔서 감사합니다🥰

전체적으로 보았을 때 이것은 **하얀 영역의 크기가 바뀌지 않아서** 생기는 비대칭 문제였습니다.
- 현재 문제가 보이는 하얀 영역의 height는 85vh로 되어있습니다. 문제는 vh를 연산할 때 하단의 주소창을 포함하여 연산한다는 것입니다. 그래서 `calc(var(--vh) * 85)`로 설정하고 있었으나, --vh 변수가 처음에만 계산되고 브라우저의 화면 크기가 바뀔 때는 **변수 값이 바뀌지 않는다**는 문제가 있었습니다. 현재는 브라우저 크기가 바뀔 때마다 변수 값이 변동됩니다.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/64337152/147407880-99cd1cc5-beb0-41c0-a8ac-01a0ccce13fe.png">

https://user-images.githubusercontent.com/64337152/147408131-1c48ff1a-f290-4e3c-9a4f-872dd9265eaf.mov
