### ISSUE TITLE
공유 기능 구현 - 인스타그램(instagram)

### ISSUE THREAD

**Issue by hotbreakb** [MBTImaker/MBTImaker-javascript-frontend#76]
## 기존 사항에 대한 문제점 / 구현 사항
- 인스타는 공유하는 기능이 없다. 페이스북이랑 똑같을 줄 알았다.
- 공유 대상에 '인스타 피드'가 없다. 다른 SNS처럼 할 수가 없다.
<img width="384" alt="image" src="https://user-images.githubusercontent.com/64337152/140603442-25d73c09-1f98-4ca8-a241-dfcdf08a8dd4.png">

## 고려했던 대안 설명
- 디자이너와 논의중이다. 나의 의견은 인스타 버튼을 눌렀을 때 결과를 이미지로 다운받을 수 있게 하는 것이다. (17:34 / 2021.11.06)

**Comment by y55mun** [comment]
<12/02 전달 받은 사항>
- 이미지 다운 기능) html로 download라는 태그가 있지만, 지원하는 브라우저가 한정적이여서 다른 방법 모색 중

**Comment by hotbreakb** [comment]
html download가 [IE만 지원을 하지 않는 거](https://developer.mozilla.org/ko/docs/Web/HTML/Element/a)라서 사용하기로 했다.

`<a href="../imgs/share_img_test.png" class="instagram" download="나의 영화 캐릭터 유형은?.png"></a>`
인스타그램 버튼을 클릭했을 때 다운로드가 된다.

href에 들어가는 링크에 상대주소만 넣을 수 있고 `https://`가 들어가는 링크는 넣을 수 없다. 로컬에 있는 이미지를 넣어야 한다. [참고](https://github.com/Redocly/redoc/issues/1247)

**Comment by hotbreakb** [comment]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/64337152/144982217-1eb04f97-aa19-4103-99ba-f679014f9476.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/64337152/144982230-28fd7164-11a8-4d13-a156-da81b940f4a7.PNG">

- 기타 -> 옵션 선택 가능 -> 이미지 저장
